services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: campo
      POSTGRES_PASSWORD: campo
      POSTGRES_DB: campo_db
    ports:
      - "5432:5432"
    volumes:
      - campo_db_data:/var/lib/postgresql/data

  observabilidad:
    image: grafana/otel-lgtm
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

volumes:
  campo_db_data: